# Generated by Django 3.1.5 on 2021-07-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_auto_20210722_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
    ]
