# Generated by Django 3.1.5 on 2021-07-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_auto_20210727_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['company']},
        ),
    ]
